# Generated by Django 3.2.5 on 2021-09-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='compulsory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
